### ISSUE TITLE
Request for a Vue 3 example

### ISSUE THREAD

**Issue by Archetipo95** [ShaunEvening/storybook-tailwind-recipe-example#2]
Hello,
I am currently trying to use the library in my Vue project, I noticed that the library examples are currently only based on React.

Is it possible to provide a simple Vue 3 example or an updated documentation that covers Vue 3 for your library? This will not only help Vue 3 users to use your library but also showcase the compatibility of your library with the latest version of Vue.

Thank you for your consideration, and I look forward to hearing back from you.

Best regards, Martin

**Comment by ShaunEvening** [comment]
Hey @Archetipo95 👋 

Thank you for reaching out 😁 Are you looking specifically for Vue 3 + tailwind? I have an example of [Vue 3 + Vuetify](https://github.com/Integrayshaun/vue3-vuetify-storybook-recipe-example) that might be of interest to you

**Comment by Archetipo95** [comment]
Yes I was looking for Vue 3 and TailwindCSS ☝🏻

Sorry if Open an issue here was not the best place to ask for this.

**Comment by ShaunEvening** [comment]
@Archetipo95 Here you go 😀 I whipped something up quickly in stackblitz
https://stackblitz.com/edit/github-rye2j5?file=.storybook/preview.ts
